"""updated the user model

Revision ID: 7c0f94da12d3
Revises: d79236dfcd52
Create Date: 2025-09-09 19:56:09.645437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0f94da12d3'
down_revision: Union[str, Sequence[str], None] = 'd79236dfcd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcmtoken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcmtoken')
    # ### end Alembic commands ###
