"""modified notification tables

Revision ID: d79236dfcd52
Revises: 8f553b445cf0
Create Date: 2025-08-19 06:58:19.549679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79236dfcd52'
down_revision: Union[str, Sequence[str], None] = '8f553b445cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'image')
    op.drop_column('notifications', 'link')
    # ### end Alembic commands ###
